# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

#prod环境配置

#端口
server:
  port: 8080

medical:
  muti-datasource-open: true #是否开启多数据源,并开启jta事务(true/false)

#druid单数据源
mysql:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bus?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat

#redis配置
spring:
  redis:
    host: 127.0.0.1
    password: admin
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

#jta + DruidXADataSource多数据源配置
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: false

    atomikos:
      datasource:
        bus:
          unique-resource-name: bus
          max-pool-size: 10
          min-pool-size: 1
          pool-size: 5
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          xa-properties:
            username: root
            password: root
            url: jdbc:mysql://localhost:3306/bus?useUnicode=true&characterEncoding=utf-8

        pay:
          unique-resource-name: pay
          max-pool-size: 10
          min-pool-size: 1
          pool-size: 5
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          xa-properties:
            username: root
            password: root
            url: jdbc:mysql://localhost:3306/pay?useUnicode=true&characterEncoding=utf-8

        user:
          unique-resource-name: user
          max-pool-size: 10
          min-pool-size: 1
          pool-size: 5
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.alibaba.druid.pool.xa.DruidXADataSource
          xa-properties:
            username: root
            password: root
            url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8